// SPDX-License-Identifier: MIT
// Copyright (c) 2026 xiyannan
// Project: Codex Remote Bridge
const els={threads:document.querySelector('#threads'),search:document.querySelector('#search'),count:document.querySelector('#count'),title:document.querySelector('#title'),meta:document.querySelector('#meta'),messages:document.querySelector('#messages'),refresh:document.querySelector('#refresh'),mode:document.querySelector('#mode'),loadMore:document.querySelector('#load-more'),quota:document.querySelector('#quota'),menu:document.querySelector('#menu'),backdrop:document.querySelector('#sidebar-backdrop'),authGate:document.querySelector('#auth-gate'),authMessage:document.querySelector('#auth-message'),authRetry:document.querySelector('#auth-retry')};
let threads=[],selected=null,selectedProjectCwd=null,threadLoading=false,lastThreadSignature='',nextCursor=null,runtimeConfig={projectsRoot:'',standaloneDir:''};
const mobileDevice=/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent)||navigator.maxTouchPoints>1&&Math.min(screen.width,screen.height)<900;
document.body.classList.toggle('mobile-ui',mobileDevice);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pathPattern=/[A-Za-z]:\\[^\r\n<>"|?*]+/g,imageExtensions=new Set(['jpg','jpeg','png','webp','gif','bmp','ico','tiff','heic']);

function projectName(cwd){if(!cwd)return'未归类项目';const parts=String(cwd).replace(/[\\/]+$/,'').split(/[\\/]/);return parts.at(-1)||'未归类项目';}
function statusLabel(status){let value=status;if(typeof value==='string'&&value.trim().startsWith('{')){try{value=JSON.parse(value);}catch{}}const type=typeof value==='object'&&value?value.type:value;return({active:'当前已加载',notLoaded:'空闲',completed:'已完成',failed:'失败',interrupted:'已中断'}[type]||type||'未知');}
function renderThreads(){const q=els.search.value.trim().toLowerCase(),filtered=threads.filter(t=>`${t.name} ${projectName(t.cwd)} ${t.cwd||''} ${t.id||''}`.toLowerCase().includes(q)),groups=new Map();for(const t of filtered){const cwd=t.cwd||'';if(!groups.has(cwd))groups.set(cwd,[]);groups.get(cwd).push(t);}els.count.textContent=`${filtered.length} 个对话 · ${groups.size} 个项目`;els.threads.innerHTML=[...groups].map(([cwd,items])=>`<section class="project-group"><button class="project-heading ${selectedProjectCwd===cwd?'selected':''}" data-project-cwd="${esc(cwd)}" title="点击在此项目中新建对话"><span>${esc(projectName(cwd))}</span><small>${items.length} ＋</small></button>${items.map(t=>{const number=threads.findIndex(x=>x.id===t.id)+1;return`<button class="thread ${selected===t.id?'active':''}" data-id="${esc(t.id)}"><div class="thread-title"><span class="thread-number">${number}</span>${esc(t.name)}</div><div class="thread-meta"><span class="status-dot"></span>${esc(statusLabel(t.status))}<span class="thread-id" title="点击复制 /绑定 命令" data-copy-id="${esc(t.id)}">ID ${esc(String(t.id||'').slice(-8))}</span></div></button>`;}).join('')}</section>`).join('');document.querySelectorAll('.project-heading').forEach(b=>b.onclick=()=>openNewThread('existing',b.dataset.projectCwd));document.querySelectorAll('.thread').forEach(b=>b.onclick=()=>loadThread(b.dataset.id));document.querySelectorAll('[data-copy-id]').forEach(el=>el.onclick=async event=>{event.stopPropagation();await navigator.clipboard.writeText(`/绑定 ${el.dataset.copyId}`);const old=el.textContent;el.textContent='已复制';setTimeout(()=>el.textContent=old,1200);});els.loadMore.hidden=!nextCursor;}
const validThreadId=value=>/^(?:urn:uuid:)?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(String(value||''));
async function loadThreads(append=false){els.refresh.disabled=true;els.loadMore.disabled=true;try{const url=`/api/threads?limit=50${append&&nextCursor?`&cursor=${encodeURIComponent(nextCursor)}`:''}`,d=await(await fetch(url)).json();const incoming=(d.threads||[]).filter(t=>validThreadId(t.id));threads=append?[...threads,...incoming.filter(t=>!threads.some(old=>old.id===t.id))]:incoming;nextCursor=d.nextCursor||null;renderThreads();}finally{els.refresh.disabled=false;els.loadMore.disabled=false;}}
function renderActivityStatus(data){const count=Number(data.activeCount||0),items=data.activeThreads||[];activityButton.hidden=count<1;activityButton.textContent=count>1?`正在运行 ${count} 个`:'正在运行 1 个';activityDetails.innerHTML=`<strong>正在运行的任务</strong>${items.length?items.map(item=>`<button class="activity-item" data-active-thread="${esc(item.id)}"><span>${esc(item.name||'正在运行的对话')}</span><small>${esc(projectName(item.cwd))} · 点击切换</small></button>`).join(''):'<div class="activity-item"><span>Codex 正在处理</span><small>正在等待具体对话状态同步</small></div>'}`;document.querySelectorAll('[data-active-thread]').forEach(button=>button.onclick=()=>{activityDetails.hidden=true;loadThread(button.dataset.activeThread);});}async function loadStatus(){try{const d=await(await fetch('/api/status',{cache:'no-store'})).json(),currentIds=new Set((d.activeThreads||[]).map(item=>item.id));if(selected&&lastGlobalActiveIds.has(selected)&&!currentIds.has(selected))selectedCompletedUntil=Date.now()+3000;lastGlobalActiveIds=currentIds;renderActivityStatus(d);els.mode.textContent=d.label;els.mode.className=`mode ${d.mode}`;if(d.mode==='restarting'){serviceRestartLatched=true;taskStrip.hidden=false;taskStrip.textContent=`服务即将重启，请约 ${d.seconds||20} 秒后刷新`;taskStrip.className='task-strip restart';}else if(d.mode==='offline'&&!serviceRestartLatched){serviceOfflineNotice=true;showTask('服务中断，请检查主机状态',true);}else if(d.online&&!serviceRestartLatched){serviceOfflineNotice=false;if(!activeWebTaskId&&!waitingForThreadCompletion){if(selected&&currentIds.has(selected))showTask('当前对话正在处理');else if(selected&&Date.now()<selectedCompletedUntil)showTask('当前对话已完成');else showTask('');}}}catch{if(!serviceRestartLatched){serviceOfflineNotice=true;showTask('公网状态暂时无法读取，正在重试…',true);}els.mode.textContent='状态连接中';els.mode.className='mode detecting';}}
async function loadQuota(){try{const d=await(await fetch('/api/quota')).json();if(!d.available)throw new Error();const reset=d.resetsAt?new Date(d.resetsAt*1000).toLocaleString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'}):'未知',synced=d.syncedAt?new Date(d.syncedAt*1000).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'未知',plan=String(d.planType||'未知').toUpperCase();els.quota.querySelector('strong').textContent=`剩余 ${d.remainingPercent}%`;els.quota.querySelector('i').style.width=`${d.remainingPercent}%`;els.quota.title='点击查看额度详情';quotaDetails.innerHTML=`<strong>Codex 额度详情</strong><span>当前套餐：${esc(plan)}</span><span>已使用：${esc(d.usedPercent)}%</span><span>额度刷新：${esc(reset)}</span><span>数据同步：${esc(synced)}</span>`;}catch{els.quota.querySelector('strong').textContent='等待首次同步';quotaDetails.innerHTML='<span>暂时没有可用的额度数据。</span>';}}
function itemText(i){if(!i)return'';if(i.type==='userMessage')return(i.content||[]).filter(x=>x.type==='text').map(x=>x.text||'').join('\n');if(i.type==='agentMessage')return i.text||'';return'';}
function reasoningText(i){const s=i.summary??i.summaries??i.text??i.content??'';if(Array.isArray(s))return s.map(x=>typeof x==='string'?x:(x.text||JSON.stringify(x))).join('\n\n');return typeof s==='string'?s:JSON.stringify(s,null,2);}
function renderItem(i){const t=itemText(i);if(i.type==='agentMessage'&&i.phase==='commentary')return t?`<div class="commentary">${esc(t)}</div>`:'';if(i.type==='reasoning'){const c=reasoningText(i)||'本条没有可显示的推理摘要。';return`<details class="reasoning-card"><summary><span>推理摘要</span><span class="expand-hint">展开查看</span></summary><div class="reasoning-body">${esc(c)}</div></details>`;}if(['commandExecution','fileChange','mcpToolCall','dynamicToolCall'].includes(i.type))return`<details class="tool"><summary>${esc(i.type)}</summary><pre>${esc(JSON.stringify(i,null,2))}</pre></details>`;return'';}
function cleanPath(v){return v.replace(/[\s.,:;，。；：）)\]}]+$/,'');}
function attachmentPaths(items){const found=[];for(const i of items){found.push(...((itemText(i).match(pathPattern)||[]).map(cleanPath)));if(i.type==='fileChange')for(const c of(i.changes||[]))if(/^[A-Za-z]:\\/.test(c.path||''))found.push(c.path);}return[...new Set(found)];}
function renderAttachments(turn){const files=turn.bridgeAttachments||[];if(!files.length)return'';return`<section class="attachments"><div class="attachment-heading">返回的文件</div>${files.map(file=>{const ext=(file.name.split('.').pop()||'').toLowerCase(),cloud=file.delivery==='cloud'&&file.cloudFileId,src=cloud?`/api/output-files/${encodeURIComponent(file.cloudFileId)}`:'',preview=cloud&&imageExtensions.has(ext)?`<a href="${src}" target="_blank" rel="noopener"><img class="attachment-preview" src="${src}" alt="${esc(file.name)}" loading="lazy"></a>`:'',lines=cloud?`<span>点击查看或下载</span><span>本机原文件：${esc(file.localPath||'')}</span><span>云端临时副本：保留 7 天</span>`:file.delivery==='agent_disk'?`<span>Agent Disk：${esc(file.agentDiskPath||file.localPath||'')}</span><span>${esc(file.reason||'')}</span>`:`<span>本机文件：${esc(file.localPath||'')}</span><span>${esc(file.reason||'')}</span>`,actions=cloud?`<div class="attachment-actions"><a href="${src}" target="_blank" rel="noopener">查看 / 下载</a></div>`:'';return`<div class="attachment-card">${preview}<div class="attachment-info"><strong>${esc(file.name)}</strong>${lines}</div>${actions}</div>`;}).join('')}</section>`;}
function bindAttachmentButtons(){document.querySelectorAll('[data-open-path]').forEach(b=>b.onclick=async()=>{const original=b.textContent;b.disabled=true;b.textContent='正在打开…';try{const r=await fetch(`/api/open-attachment?path=${encodeURIComponent(b.dataset.openPath)}`);if(!r.ok)throw new Error();b.textContent='已打开';}catch{b.textContent='文件不存在';}setTimeout(()=>{b.disabled=false;b.textContent=original;},1800);} );}
function renderTurns(turns){if(!turns.length)return'<div class="empty"><h3>暂无历史</h3><p>从网页或飞书向该对话发送第一条消息。</p></div>';return turns.map(turn=>{const items=turn.items||[],users=items.filter(x=>x.type==='userMessage'),agents=items.filter(x=>x.type==='agentMessage'),final=[...agents].reverse().find(x=>x.phase!=='commentary'),middle=items.filter(x=>!users.includes(x)&&x!==final).map(renderItem).join(''),answer=itemText(final)||(agents.length?itemText(agents.at(-1)):'（尚无最终回答）'),userBlocks=users.map((user,index)=>`<div class="user ${index?'steering-user':''}"><div class="label">${index?'补充引导':'你'}</div><div class="bubble">${esc(itemText(user)||'（非文字输入）')}</div></div>`).join('');return`<article class="turn">${userBlocks}${middle}<div class="assistant"><div class="label">Codex</div><div class="bubble">${esc(answer)}</div></div>${renderAttachments(turn)}</article>`;}).join('');}
async function loadThread(id,silent=false){if(threadLoading)return;threadLoading=true;selected=id;renderThreads();if(!silent)els.messages.innerHTML='<div class="loading">正在读取完整历史…</div>';try{const data=await(await fetch(`/api/thread/${encodeURIComponent(id)}`)).json();if(data.error){if(!silent)els.messages.innerHTML=`<div class="loading">${esc(data.error)}</div>`;return;}const t=data.thread,signature=JSON.stringify((t.turns||[]).map(turn=>[turn.id,turn.status,(turn.items||[]).length]));els.title.textContent=t.name||'未命名对话';els.meta.textContent=`项目：${projectName(t.cwd)} · ${statusLabel(t.status)} · ${(t.turns||[]).length} 轮 · ID：${t.id||id}`;if(!silent||signature!==lastThreadSignature){const nearBottom=els.messages.scrollHeight-els.messages.scrollTop-els.messages.clientHeight<140;els.messages.innerHTML=renderTurns(t.turns||[]);bindAttachmentButtons();if(!silent||nearBottom)els.messages.scrollTop=els.messages.scrollHeight;lastThreadSignature=signature;}}finally{threadLoading=false;}}
function requestFeishuCode(appId){return new Promise((resolve,reject)=>{if(!window.tt?.requestAccess){const back=location.pathname+location.search+location.hash;location.replace(`/api/auth/oauth/start?return_to=${encodeURIComponent(back)}`);return;}window.tt.requestAccess({appID:appId,scopeList:[],success:r=>resolve(r.code),fail:r=>reject(new Error(r?.errMsg||'飞书授权失败'))});});}
async function authenticate(){els.authGate.hidden=false;els.authRetry.hidden=true;els.authMessage.textContent='正在连接飞书并确认身份…';try{const config=await(await fetch('/api/auth/config',{cache:'no-store'})).json();runtimeConfig={projectsRoot:config.projectsRoot||'',standaloneDir:config.standaloneDir||''};if(!config.authRequired||config.authenticated){els.authGate.hidden=true;return true;}if(!config.ownerConfigured)throw new Error('桥尚未绑定所有者，请先在机器人单聊中发送一条消息');const code=await requestFeishuCode(config.appId);const response=await fetch('/api/auth/feishu',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const result=await response.json();if(!response.ok)throw new Error(result.error==='owner_mismatch'?'当前飞书账号不是桥的所有者':(result.message||'身份验证失败'));els.authGate.hidden=true;return true;}catch(error){els.authMessage.textContent=error.message||'身份验证失败';els.authRetry.hidden=false;return false;}}
const composer=document.querySelector('#composer'),promptBox=document.querySelector('#prompt'),sendButton=document.querySelector('#send'),taskStrip=document.querySelector('#task-strip'),newThreadButton=document.querySelector('#new-thread'),fileInput=document.querySelector('#files'),fileList=document.querySelector('#file-list'),quotaDetails=document.querySelector('#quota-details'),activityButton=document.querySelector('#activity'),activityDetails=document.querySelector('#activity-details');
const threadMenu=document.querySelector('#thread-menu'),hideThreadButton=document.querySelector('#hide-thread'),cancelThreadMenu=document.querySelector('#cancel-thread-menu');
const newThreadDialog=document.querySelector('#new-thread-dialog'),newThreadForm=document.querySelector('#new-thread-form'),newThreadProject=document.querySelector('#new-thread-project'),newProjectName=document.querySelector('#new-project-name'),newThreadTitle=document.querySelector('#new-thread-title'),newThreadText=document.querySelector('#new-thread-text'),existingProjectRow=document.querySelector('#existing-project-row'),newProjectRow=document.querySelector('#new-project-row'),newThreadLocation=document.querySelector('#new-thread-location');
let activeWebTaskId=null,lastTaskEventId=0,activeTaskPreview='',waitingForThreadCompletion=false,completionTimer=null,steeredThreadId=null,steeredTurnId=null,serviceRestartLatched=false,serviceOfflineNotice=false,lastGlobalActiveIds=new Set(),selectedCompletedUntil=0;
els.quota.onclick=event=>{event.stopPropagation();quotaDetails.hidden=!quotaDetails.hidden;};quotaDetails.onclick=event=>event.stopPropagation();document.addEventListener('click',()=>quotaDetails.hidden=true);
activityButton.onclick=event=>{event.stopPropagation();activityDetails.hidden=!activityDetails.hidden;};activityDetails.onclick=event=>event.stopPropagation();document.addEventListener('click',()=>activityDetails.hidden=true);
let menuThreadId=null,longPressTimer=null,menuOpenedAt=0;
function closeThreadMenu(){threadMenu.hidden=true;menuThreadId=null;}
function openThreadMenu(threadId,x,y){menuThreadId=threadId;menuOpenedAt=Date.now();threadMenu.hidden=false;const width=180,height=100;threadMenu.style.left=Math.max(8,Math.min(x,innerWidth-width-8))+'px';threadMenu.style.top=Math.max(8,Math.min(y,innerHeight-height-8))+'px';}
els.threads.addEventListener('contextmenu',event=>{const row=event.target.closest('.thread');if(!row)return;event.preventDefault();openThreadMenu(row.dataset.id,event.clientX,event.clientY);});
els.threads.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse')return;const row=event.target.closest('.thread');if(!row)return;longPressTimer=setTimeout(()=>openThreadMenu(row.dataset.id,event.clientX,event.clientY),650);});
for(const name of ['pointerup','pointercancel','pointermove'])els.threads.addEventListener(name,()=>{clearTimeout(longPressTimer);longPressTimer=null;});
cancelThreadMenu.onclick=closeThreadMenu;
threadMenu.onclick=event=>event.stopPropagation();document.addEventListener('click',()=>{if(Date.now()-menuOpenedAt>500)closeThreadMenu();});
hideThreadButton.onclick=async()=>{const threadId=menuThreadId;if(!threadId)return;const item=threads.find(thread=>thread.id===threadId);if(!confirm(`只从网页列表移除“${item?.name||'这个对话'}”？\n\n不会删除 Codex 客户端中的对话或历史。`))return;try{const response=await fetch('/api/threads/hide',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({threadId})});if(!response.ok)throw new Error('移除失败');threads=threads.filter(thread=>thread.id!==threadId);if(selected===threadId){selected=null;els.title.textContent='选择一个对话';els.meta.textContent='该对话仅从网页列表隐藏，Codex 客户端未受影响';els.messages.innerHTML='<div class="empty"><h3>已从网页列表移除</h3><p>本机 Codex 对话和历史没有删除。</p></div>';}renderThreads();showTask('已从网页列表移除，不影响 Codex 客户端');setTimeout(()=>showTask(''),3500);}catch(error){showTask(error.message,true);}finally{closeThreadMenu();}};
function showTask(message,error=false){if(serviceRestartLatched)return;taskStrip.hidden=!message;taskStrip.textContent=message||'';taskStrip.className=`task-strip${error?' error':''}`;}
function saveActiveTask(){if(activeWebTaskId)sessionStorage.setItem('codex-active-task',JSON.stringify({id:activeWebTaskId,eventId:lastTaskEventId,preview:activeTaskPreview}));else sessionStorage.removeItem('codex-active-task');}
function restoreActiveTask(){try{const saved=JSON.parse(sessionStorage.getItem('codex-active-task')||'null');if(saved?.id){activeWebTaskId=saved.id;lastTaskEventId=Number(saved.eventId)||0;activeTaskPreview=saved.preview||'正在处理';showTask(`正在恢复任务状态：${activeTaskPreview}`);}}catch{sessionStorage.removeItem('codex-active-task');}}
async function submitTask(payload){const response=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok){const labels={file_too_large:'附件过大：单文件最多10 MB，单次最多15 MB',unsupported_file_type:'不支持这种文件格式',too_many_files:'一次最多上传3个文件'};throw new Error(labels[data.error]||data.error||'任务提交失败');}activeWebTaskId=data.taskId;lastTaskEventId=0;activeTaskPreview=String(payload.text||payload.title||'附件任务').replace(/\s+/g,' ').trim().slice(0,80);saveActiveTask();showTask(`已提交：${activeTaskPreview}`);return data;}
function fileData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,mime:file.type||'application/octet-stream',data:String(reader.result).split(',',2)[1]||''});reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});}
let deliberateSubmit=false;
sendButton.addEventListener('click',()=>{deliberateSubmit=true;});
function clearPendingFiles(){fileInput.value='';fileList.hidden=true;fileList.innerHTML='';}
fileInput.onchange=()=>{const files=[...fileInput.files];fileList.hidden=!files.length;if(!files.length){fileList.innerHTML='';return;}fileList.innerHTML=`<span>待发送：${files.map(file=>`${esc(file.name)}（${(file.size/1024/1024).toFixed(1)} MB）`).join('、')} · 可继续填写问题描述，确认后再点发送</span><button id="clear-files" type="button">取消附件</button>`;document.querySelector('#clear-files').onclick=clearPendingFiles;};
composer.onsubmit=async event=>{event.preventDefault();const isDeliberate=event.submitter===sendButton||deliberateSubmit;deliberateSubmit=false;if(!isDeliberate)return;let textValue=promptBox.value.trim();const chosen=[...fileInput.files];if(!selected){showTask('请先选择一个对话',true);return;}if(!textValue&&!chosen.length)return;if(chosen.length>3||chosen.some(file=>file.size>10*1024*1024)||chosen.reduce((sum,file)=>sum+file.size,0)>15*1024*1024){showTask('附件限制：最多3个，单文件10 MB，单次总计15 MB',true);return;}sendButton.disabled=true;try{const files=await Promise.all(chosen.map(fileData));await submitTask({op:'message',threadId:selected,text:textValue||'请查看并处理我从网页上传的附件。',files});promptBox.value='';promptBox.style.height='';clearPendingFiles();}catch(error){showTask(error.message,true);}finally{sendButton.disabled=false;promptBox.focus();}};
promptBox.oninput=()=>{promptBox.style.height='auto';promptBox.style.height=Math.min(promptBox.scrollHeight,180)+'px';};
promptBox.onkeydown=event=>{if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)){event.preventDefault();deliberateSubmit=true;composer.requestSubmit(sendButton);}};
function newThreadKind(){return new FormData(newThreadForm).get('thread-kind')||'existing';}
function joinWindowsPath(root,name){return String(root||'').replace(/[\\/]+$/,'')+'\\'+name;}
function refreshNewThreadForm(){const kind=newThreadKind();existingProjectRow.hidden=kind!=='existing';newProjectRow.hidden=kind!=='project';const cwd=kind==='standalone'?runtimeConfig.standaloneDir:kind==='project'?joinWindowsPath(runtimeConfig.projectsRoot,newProjectName.value.trim()||'项目名称'):newThreadProject.value;newThreadLocation.textContent=`本机目录：${cwd||'安装时尚未配置此目录'}`;}
function openNewThread(kind='existing',cwd=null){const projects=[...new Map(threads.filter(t=>t.cwd).map(t=>[t.cwd,t])).keys()];newThreadProject.innerHTML=projects.map(path=>`<option value="${esc(path)}">${esc(projectName(path))} — ${esc(path)}</option>`).join('');const preferred=cwd||threads.find(t=>t.id===selected)?.cwd||selectedProjectCwd||projects[0]||'';if(preferred)newThreadProject.value=preferred;selectedProjectCwd=preferred||null;newThreadForm.querySelector(`input[name="thread-kind"][value="${kind}"]`).checked=true;newThreadTitle.value='';newThreadText.value='';newProjectName.value='';refreshNewThreadForm();newThreadDialog.showModal();setTimeout(()=>newThreadTitle.focus(),50);renderThreads();}
newThreadForm.querySelectorAll('input[name="thread-kind"]').forEach(input=>input.onchange=refreshNewThreadForm);newThreadProject.onchange=refreshNewThreadForm;newProjectName.oninput=refreshNewThreadForm;
document.querySelector('#close-new-thread').onclick=()=>newThreadDialog.close();document.querySelector('#cancel-new-thread').onclick=()=>newThreadDialog.close();
newThreadButton.onclick=()=>openNewThread('existing');
newThreadForm.onsubmit=async event=>{event.preventDefault();const kind=newThreadKind(),project=newProjectName.value.trim();if(kind==='project'&&(!project||/[<>:"/\\|?*]/.test(project))){showTask('项目名称不能为空，也不能包含路径特殊字符',true);return;}const cwd=kind==='standalone'?runtimeConfig.standaloneDir:kind==='project'?joinWindowsPath(runtimeConfig.projectsRoot,project):newThreadProject.value,title=newThreadTitle.value.trim(),text=newThreadText.value.trim();if(!cwd){showTask('请先在安装配置中设置项目或独立会话目录',true);return;}if(!title||!text)return;try{await submitTask({op:'new_thread',cwd,title,text});newThreadDialog.close();selectedProjectCwd=cwd;els.title.textContent=title;els.meta.textContent=`正在创建 · 项目：${projectName(cwd)}`;els.messages.innerHTML='<div class="loading">正在创建新对话并发送第一条消息…</div>';renderThreads();}catch(error){showTask(error.message,true);}};
async function selectCreatedThread(payload){if(!payload.threadId)return;selected=payload.threadId;selectedProjectCwd=payload.cwd||selectedProjectCwd;els.title.textContent=payload.title||els.title.textContent||'新对话';els.meta.textContent='新对话已创建，正在等待历史同步';renderThreads();await loadThreads(false);if(threads.some(thread=>thread.id===selected))await loadThread(selected,true);}
async function pollTask(){if(!activeWebTaskId)return;try{const response=await fetch(`/api/task/${encodeURIComponent(activeWebTaskId)}/events?after=${lastTaskEventId}`),data=await response.json();for(const event of data.events||[]){lastTaskEventId=Math.max(lastTaskEventId,event.id);const p=event.payload||{};if(event.kind==='created'){await selectCreatedThread(p);showTask(`新对话已创建，正在执行第一条消息：${p.title||activeTaskPreview}`);}else if(event.kind==='progress')showTask(`Codex 正在处理\n\n${p.summary||''}`);else if(event.kind==='steered'){waitingForThreadCompletion=true;steeredThreadId=selected;steeredTurnId=p.turnId||null;clearTimeout(completionTimer);showTask(`Codex 仍在处理 · 已追加：${activeTaskPreview}`);activeWebTaskId=null;saveActiveTask();if(selected)loadThread(selected,true);}else if(event.kind==='queued')showTask(`等待本机接收：${activeTaskPreview}`);else if(event.kind==='started')showTask(`Codex 已开始：${activeTaskPreview}`);else if(event.kind==='final'){waitingForThreadCompletion=false;steeredThreadId=null;steeredTurnId=null;showTask('任务已完成');await loadThreads(false);if(selected)loadThread(selected,true);clearTimeout(completionTimer);completionTimer=setTimeout(()=>showTask(''),3000);activeWebTaskId=null;saveActiveTask();}else if(event.kind==='completed'){await selectCreatedThread(p);activeWebTaskId=null;saveActiveTask();showTask(p.message||'新对话已创建');}else if(event.kind==='error'){waitingForThreadCompletion=false;steeredThreadId=null;steeredTurnId=null;showTask(p.message||'任务失败',true);activeWebTaskId=null;saveActiveTask();}else showTask(p.message||event.kind);saveActiveTask();}}catch(error){showTask('实时状态暂时断开，正在重试…',true);}}
async function monitorSteeredThread(){if(!waitingForThreadCompletion||!steeredThreadId||!steeredTurnId)return;try{const data=await(await fetch(`/api/thread/${encodeURIComponent(steeredThreadId)}`)).json(),turns=data.thread?.turns||[],turn=turns.find(item=>item.id===steeredTurnId);if(!turn){showTask(`Codex 仍在处理 · 已追加：${activeTaskPreview}`);return;}const raw=turn.status,status=typeof raw==='object'&&raw?raw.type:raw;if(['completed','failed','interrupted','cancelled'].includes(status)){waitingForThreadCompletion=false;steeredThreadId=null;steeredTurnId=null;showTask(status==='completed'?'任务已完成':`任务已结束：${status}`);if(selected)loadThread(selected,true);clearTimeout(completionTimer);completionTimer=setTimeout(()=>showTask(''),3000);}else showTask(`Codex 仍在处理 · 已追加：${activeTaskPreview}`);}catch{}}
async function boot(){if(!await authenticate())return;restoreActiveTask();loadThreads();loadStatus();loadQuota();setInterval(()=>loadThreads(false),10000);setInterval(loadStatus,3000);setInterval(loadQuota,60000);setInterval(()=>{if(selected)loadThread(selected,true);},1000);setInterval(pollTask,700);setInterval(monitorSteeredThread,1000);}
els.authRetry.onclick=boot;els.menu.onclick=()=>document.body.classList.add('sidebar-open');els.backdrop.onclick=()=>document.body.classList.remove('sidebar-open');els.search.oninput=renderThreads;els.refresh.onclick=()=>{loadThreads();if(selected)loadThread(selected,true);};els.loadMore.onclick=()=>loadThreads(true);boot();
