// SPDX-License-Identifier: MIT
// Copyright (c) 2026 xiyannan
// Project: Codex Remote Bridge
// PAIRED UI CONTRACT: keep conversation loading and interaction behavior aligned with the sibling web app.
const els={threads:document.querySelector('#threads'),search:document.querySelector('#search'),count:document.querySelector('#count'),title:document.querySelector('#title'),meta:document.querySelector('#meta'),messages:document.querySelector('#messages'),refresh:document.querySelector('#refresh'),mode:document.querySelector('#mode'),loadMore:document.querySelector('#load-more'),quota:document.querySelector('#quota'),quotaDetails:document.querySelector('#quota-details'),menu:document.querySelector('#menu'),backdrop:document.querySelector('#sidebar-backdrop'),authGate:document.querySelector('#auth-gate'),authMessage:document.querySelector('#auth-message'),authRetry:document.querySelector('#auth-retry')};
let threads=[],selected=null,threadLoading=false,lastThreadSignature='',nextCursor=null,threadVisibleCounts=new Map(),threadRequestSerial=0,threadController=null;
const mobileDevice=/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent)||navigator.maxTouchPoints>1&&Math.min(screen.width,screen.height)<900;
document.body.classList.toggle('mobile-ui',mobileDevice);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pathPattern=/[A-Za-z]:\\[^\r\n<>"|?*]+/g,imageExtensions=new Set(['jpg','jpeg','png','webp','gif','bmp','ico','tiff','heic']);

function projectName(cwd){if(!cwd)return'未归类项目';const parts=String(cwd).replace(/[\\/]+$/,'').split(/[\\/]/);return parts.at(-1)||'未归类项目';}
function renderThreads(){const q=els.search.value.trim().toLowerCase(),filtered=threads.filter(t=>`${t.name} ${projectName(t.cwd)} ${t.cwd||''} ${t.id||''}`.toLowerCase().includes(q)),groups=new Map();for(const t of filtered){const cwd=t.cwd||'';if(!groups.has(cwd))groups.set(cwd,[]);groups.get(cwd).push(t);}els.count.textContent=`${filtered.length} 个对话 · ${groups.size} 个项目`;els.threads.innerHTML=[...groups].map(([cwd,items])=>`<section class="project-group"><button class="project-heading" data-project-cwd="${esc(cwd)}" title="点击在此项目中新建对话"><span>${esc(projectName(cwd))}</span><small>${items.length} ＋</small></button>${items.map(t=>{const number=threads.findIndex(x=>x.id===t.id)+1;return`<button class="thread ${selected===t.id?'active':''}" data-id="${esc(t.id)}"><div class="thread-title"><span class="thread-number">${number}</span>${esc(t.name)}</div><div class="thread-meta"><span class="status-dot"></span>${esc(t.status||'未知')}<span class="thread-id" title="点击复制 /绑定 命令" data-copy-id="${esc(t.id)}">ID ${esc(String(t.id||'').slice(-8))}</span></div></button>`;}).join('')}</section>`).join('');document.querySelectorAll('.project-heading').forEach(b=>b.onclick=()=>window.openLocalNewThread?.('existing',b.dataset.projectCwd));document.querySelectorAll('.thread').forEach(b=>b.onclick=()=>loadThread(b.dataset.id));document.querySelectorAll('[data-copy-id]').forEach(el=>el.onclick=async event=>{event.stopPropagation();await navigator.clipboard.writeText(`/绑定 ${el.dataset.copyId}`);const old=el.textContent;el.textContent='已复制';setTimeout(()=>el.textContent=old,1200);});els.loadMore.hidden=!nextCursor;}
async function loadThreads(append=false){els.refresh.disabled=true;els.loadMore.disabled=true;try{const url=`/api/threads?limit=50${append&&nextCursor?`&cursor=${encodeURIComponent(nextCursor)}`:''}`,d=await(await fetch(url)).json();const incoming=d.threads||[];threads=append?[...threads,...incoming.filter(t=>!threads.some(old=>old.id===t.id))]:incoming;nextCursor=d.nextCursor||null;renderThreads();}finally{els.refresh.disabled=false;els.loadMore.disabled=false;}}
async function loadStatus(){try{const d=await(await fetch('/api/status')).json();els.mode.textContent=d.label;els.mode.className=`mode ${d.mode}`;}catch{els.mode.textContent='模式状态不可用';els.mode.className='mode detecting';}}
async function loadQuota(){try{const d=await(await fetch('/api/quota')).json();if(!d.available)throw new Error();const reset=d.resetsAt?new Date(d.resetsAt*1000).toLocaleString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'}):'未知';els.quota.querySelector('strong').textContent=`剩余 ${d.remainingPercent}%`;els.quota.querySelector('i').style.width=`${d.remainingPercent}%`;els.quotaDetails.innerHTML=`<strong>Codex 额度详情</strong><span>当前套餐：${esc(String(d.planType||'未知').toUpperCase())}</span><span>已使用：${esc(d.usedPercent)}%</span><span>额度刷新：${esc(reset)}</span>`;}catch{els.quota.querySelector('strong').textContent='暂不可用';els.quotaDetails.innerHTML='<span>暂时没有可用的额度数据。</span>';}}
els.quota.onclick=event=>{event.stopPropagation();els.quotaDetails.hidden=!els.quotaDetails.hidden;};els.quotaDetails.onclick=event=>event.stopPropagation();document.addEventListener('click',()=>els.quotaDetails.hidden=true);
function itemText(i){if(!i)return'';if(i.type==='userMessage')return(i.content||[]).filter(x=>x.type==='text').map(x=>x.text||'').join('\n');if(i.type==='agentMessage')return i.text||'';return'';}
function reasoningText(i){const s=i.summary??i.summaries??i.text??i.content??'';if(Array.isArray(s))return s.map(x=>typeof x==='string'?x:(x.text||JSON.stringify(x))).join('\n\n');return typeof s==='string'?s:JSON.stringify(s,null,2);}
function renderItem(i,turn){const t=itemText(i);if(i.type==='agentMessage'&&i.phase==='commentary')return t?`<div class="commentary">${esc(t)}</div>`:'';if(i.type==='reasoning'){const c=reasoningText(i).trim();if(!c||c==='[]'||c==='{}')return'';return`<details class="reasoning-card"><summary><span>推理摘要</span><span class="expand-hint">展开查看</span></summary><div class="reasoning-body">${esc(c)}</div><div class="voice-actions">${window.voiceUI?.record(turn,i,c,'reasoning')||''}</div></details>`;}if(['commandExecution','fileChange','mcpToolCall','dynamicToolCall'].includes(i.type))return`<details class="tool"><summary>${esc(i.type)}</summary><pre>${esc(JSON.stringify(i,null,2))}</pre></details>`;return'';}
function cleanPath(v){return v.replace(/[\s.,:;，。；：）)\]}]+$/,'');}
function attachmentPaths(items){const found=[];for(const i of items){found.push(...((itemText(i).match(pathPattern)||[]).map(cleanPath)));if(i.type==='fileChange')for(const c of(i.changes||[]))if(/^[A-Za-z]:\\/.test(c.path||''))found.push(c.path);}return[...new Set(found)];}
function renderAttachments(turn){const files=turn.bridgeAttachments||[];if(!files.length)return'';return`<section class="attachments"><div class="attachment-heading">返回的文件</div>${files.map(file=>{const path=file.agentDiskPath||file.localPath,ext=(file.name.split('.').pop()||'').toLowerCase(),src=`/api/attachment?path=${encodeURIComponent(path)}`,direct=file.delivery!=='local_only',preview=direct&&imageExtensions.has(ext)?`<a href="${src}" target="_blank" rel="noopener"><img class="attachment-preview" src="${src}" alt="${esc(file.name)}" loading="lazy"></a>`:'',location=file.delivery==='agent_disk'?`Agent Disk：${path}`:`本机文件：${path}`,actions=direct?`<div class="attachment-actions"><a href="${src}" target="_blank" rel="noopener">查看 / 下载</a><button data-open-path="${esc(path)}">本机打开</button></div>`:`<div class="attachment-actions"><button data-open-path="${esc(path)}">本机打开</button></div>`;return`<div class="attachment-card">${preview}<div class="attachment-info"><strong>${esc(file.name)}</strong><span>${esc(location)}</span><span>${esc(file.reason||'')}</span></div>${actions}</div>`;}).join('')}</section>`;}
function bindAttachmentButtons(){document.querySelectorAll('[data-open-path]').forEach(b=>b.onclick=async()=>{const original=b.textContent;b.disabled=true;b.textContent='正在打开…';try{const r=await fetch(`/api/open-attachment?path=${encodeURIComponent(b.dataset.openPath)}`);if(!r.ok)throw new Error();b.textContent='已打开';}catch{b.textContent='文件不存在';}setTimeout(()=>{b.disabled=false;b.textContent=original;},1800);} );}
function renderTurns(turns){window.voiceUI?.clear(selected);if(!turns.length)return'<div class="empty"><h3>暂无历史</h3><p>从飞书向该对话发送第一条消息。</p></div>';return turns.map(turn=>{const items=turn.items||[],user=items.find(x=>x.type==='userMessage'),agents=items.filter(x=>x.type==='agentMessage'),final=[...agents].reverse().find(x=>x.phase!=='commentary'),middle=items.filter(x=>x!==user&&x!==final).map(i=>renderItem(i,turn)).join(''),answer=itemText(final)||(agents.length?itemText(agents.at(-1)):'（尚无最终回答）');return`<article class="turn"><div class="user"><div class="label">你</div><div class="bubble">${esc(itemText(user)||'（非文字输入）')}</div></div>${middle}<div class="assistant"><div class="label">Codex · ${esc(window.modelPicker?.label(turn)||'模型未记录')}</div><div class="bubble">${esc(answer)}<div class="voice-actions">${final?window.voiceUI?.record(turn,final,answer,'final')||'':''}</div></div></div>${renderAttachments(turn)}</article>`;}).join('');}
async function loadThread(id,silent=false,showOlder=false){
  if(silent&&threadLoading&&selected===id)return;
  const switching=selected!==id;
  if(switching&&!threadVisibleCounts.has(id))threadVisibleCounts.set(id,6);
  const limit=threadVisibleCounts.get(id)||6;
  if(threadController)threadController.abort();
  const controller=new AbortController(),requestId=++threadRequestSerial;
  threadController=controller;threadLoading=true;selected=id;window.modelPicker?.begin(id);renderThreads();
  if(!silent)els.messages.innerHTML='<div class="loading">正在读取最近对话…</div>';
  try{
    const response=await fetch(`/api/thread/${encodeURIComponent(id)}?turnLimit=${limit}`,{signal:controller.signal,cache:'no-store'});
    const data=await response.json();
    if(requestId!==threadRequestSerial||selected!==id)return;
    if(data.error){if(!silent)els.messages.innerHTML=`<div class="loading">${esc(data.error)}</div>`;return;}
    window.modelPicker?.thread(data.thread);
    const t=data.thread,total=Number(t.bridgeTotalTurns??(t.turns||[]).length),visible=(t.turns||[]).length;
    const signature=JSON.stringify([total,visible,(t.turns||[]).map(turn=>[turn.id,turn.status,turn.bridgeModel,(turn.items||[]).length])]);
    els.title.textContent=t.name||'未命名对话';
    els.meta.textContent=`项目：${projectName(t.cwd)} · ${t.status||'未知'} · ${total} 轮 · ID：${t.id||id}`;
    if(!silent||signature!==lastThreadSignature){
      const nearBottom=els.messages.scrollHeight-els.messages.scrollTop-els.messages.clientHeight<140,remaining=Math.max(0,total-visible);
      const older=remaining?`<div class="older-turns-wrap"><button id="load-older-turns" type="button">查看更早 6 轮（还有 ${remaining} 轮）</button><button id="load-all-turns" type="button">查看全部</button></div>`:'';
      els.messages.innerHTML=older+renderTurns(t.turns||[]);
      const olderButton=document.querySelector('#load-older-turns'),allButton=document.querySelector('#load-all-turns');
      if(olderButton)olderButton.onclick=()=>{threadVisibleCounts.set(id,Math.min(total,Number(limit)+6));loadThread(id,false,true);};
      if(allButton)allButton.onclick=()=>{threadVisibleCounts.set(id,'all');loadThread(id,false,true);};
      bindAttachmentButtons();
      window.voiceUI?.bind(id);
      if(showOlder)els.messages.scrollTop=0;else if(!silent||nearBottom)els.messages.scrollTop=els.messages.scrollHeight;
      lastThreadSignature=signature;
    }
  }catch(error){
    if(error.name!=='AbortError'&&!silent)els.messages.innerHTML='<div class="loading">读取失败，请重试</div>';
  }finally{
    if(requestId===threadRequestSerial){threadLoading=false;threadController=null;}
  }
}
async function authenticate(){els.authGate.hidden=false;els.authRetry.hidden=true;els.authMessage.textContent='正在连接飞书并确认身份…';try{const config=await(await fetch('/api/auth/config',{cache:'no-store'})).json();if(!config.authRequired||config.authenticated){els.authGate.hidden=true;return true;}if(!config.ownerConfigured)throw new Error('桥尚未绑定所有者，请先在机器人单聊中发送一条消息');const code=await requestFeishuCode(config.appId);const response=await fetch('/api/auth/feishu',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const result=await response.json();if(!response.ok)throw new Error(result.error==='owner_mismatch'?'当前飞书账号不是桥的所有者':(result.message||'身份验证失败'));els.authGate.hidden=true;return true;}catch(error){els.authMessage.textContent=error.message||'身份验证失败';els.authRetry.hidden=false;return false;}}
async function boot(){if(!await authenticate())return;await window.voiceUI?.settings();window.voiceUI?.boot();loadThreads();loadStatus();loadQuota();setInterval(()=>loadThreads(false),30000);setInterval(loadStatus,5000);setInterval(loadQuota,60000);setInterval(()=>{if(selected)loadThread(selected,true);},3000);}
els.authRetry.onclick=boot;els.menu.onclick=()=>document.body.classList.add('sidebar-open');els.backdrop.onclick=()=>document.body.classList.remove('sidebar-open');els.search.oninput=renderThreads;els.refresh.onclick=()=>{loadThreads();if(selected)loadThread(selected,true);};els.loadMore.onclick=()=>loadThreads(true);boot();
