// SPDX-License-Identifier: MIT
// Copyright (c) 2026 xiyannan
// Project: Codex Remote Bridge
const els={threads:document.querySelector('#threads'),search:document.querySelector('#search'),count:document.querySelector('#count'),title:document.querySelector('#title'),meta:document.querySelector('#meta'),messages:document.querySelector('#messages'),refresh:document.querySelector('#refresh'),mode:document.querySelector('#mode'),loadMore:document.querySelector('#load-more'),quota:document.querySelector('#quota'),menu:document.querySelector('#menu'),backdrop:document.querySelector('#sidebar-backdrop'),authGate:document.querySelector('#auth-gate'),authMessage:document.querySelector('#auth-message'),authRetry:document.querySelector('#auth-retry')};
let threads=[],selected=null,threadLoading=false,lastThreadSignature='',nextCursor=null;
const mobileDevice=/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent)||navigator.maxTouchPoints>1&&Math.min(screen.width,screen.height)<900;
document.body.classList.toggle('mobile-ui',mobileDevice);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pathPattern=/[A-Za-z]:\\[^\r\n<>"|?*]+/g,imageExtensions=new Set(['jpg','jpeg','png','webp','gif','bmp','ico','tiff','heic']);

function projectName(cwd){if(!cwd)return'未归类项目';const parts=String(cwd).replace(/[\\/]+$/,'').split(/[\\/]/);return parts.at(-1)||'未归类项目';}
function renderThreads(){const q=els.search.value.trim().toLowerCase(),filtered=threads.filter(t=>`${t.name} ${projectName(t.cwd)} ${t.cwd||''} ${t.id||''}`.toLowerCase().includes(q)),groups=new Map();for(const t of filtered){const project=projectName(t.cwd);if(!groups.has(project))groups.set(project,[]);groups.get(project).push(t);}els.count.textContent=`${filtered.length} 个对话 · ${groups.size} 个项目`;els.threads.innerHTML=[...groups].map(([project,items])=>`<section class="project-group"><div class="project-heading"><span>${esc(project)}</span><small>${items.length}</small></div>${items.map(t=>{const number=threads.findIndex(x=>x.id===t.id)+1;return`<button class="thread ${selected===t.id?'active':''}" data-id="${esc(t.id)}"><div class="thread-title"><span class="thread-number">${number}</span>${esc(t.name)}</div><div class="thread-meta"><span class="status-dot"></span>${esc(t.status||'未知')}<span class="thread-id" title="点击复制 /绑定 命令" data-copy-id="${esc(t.id)}">ID ${esc(String(t.id||'').slice(-8))}</span></div></button>`;}).join('')}</section>`).join('');document.querySelectorAll('.thread').forEach(b=>b.onclick=()=>loadThread(b.dataset.id));document.querySelectorAll('[data-copy-id]').forEach(el=>el.onclick=async event=>{event.stopPropagation();await navigator.clipboard.writeText(`/绑定 ${el.dataset.copyId}`);const old=el.textContent;el.textContent='已复制';setTimeout(()=>el.textContent=old,1200);});els.loadMore.hidden=!nextCursor;}
async function loadThreads(append=false){els.refresh.disabled=true;els.loadMore.disabled=true;try{const url=`/api/threads?limit=50${append&&nextCursor?`&cursor=${encodeURIComponent(nextCursor)}`:''}`,d=await(await fetch(url)).json();const incoming=d.threads||[];threads=append?[...threads,...incoming.filter(t=>!threads.some(old=>old.id===t.id))]:incoming;nextCursor=d.nextCursor||null;renderThreads();}finally{els.refresh.disabled=false;els.loadMore.disabled=false;}}
async function loadStatus(){try{const d=await(await fetch('/api/status')).json();els.mode.textContent=d.label;els.mode.className=`mode ${d.mode}`;}catch{els.mode.textContent='模式状态不可用';els.mode.className='mode detecting';}}
async function loadQuota(){try{const d=await(await fetch('/api/quota')).json();if(!d.available)throw new Error();const reset=d.resetsAt?new Date(d.resetsAt*1000).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'未知';els.quota.querySelector('strong').textContent=`剩余 ${d.remainingPercent}%`;els.quota.querySelector('i').style.width=`${d.remainingPercent}%`;els.quota.title=`${String(d.planType||'').toUpperCase()} · 已使用 ${d.usedPercent}% · ${reset} 重置`;}catch{els.quota.querySelector('strong').textContent='暂不可用';}}
function itemText(i){if(!i)return'';if(i.type==='userMessage')return(i.content||[]).filter(x=>x.type==='text').map(x=>x.text||'').join('\n');if(i.type==='agentMessage')return i.text||'';return'';}
function reasoningText(i){const s=i.summary??i.summaries??i.text??i.content??'';if(Array.isArray(s))return s.map(x=>typeof x==='string'?x:(x.text||JSON.stringify(x))).join('\n\n');return typeof s==='string'?s:JSON.stringify(s,null,2);}
function renderItem(i){const t=itemText(i);if(i.type==='agentMessage'&&i.phase==='commentary')return t?`<div class="commentary">${esc(t)}</div>`:'';if(i.type==='reasoning'){const c=reasoningText(i)||'本条没有可显示的推理摘要。';return`<details class="reasoning-card"><summary><span>推理摘要</span><span class="expand-hint">展开查看</span></summary><div class="reasoning-body">${esc(c)}</div></details>`;}if(['commandExecution','fileChange','mcpToolCall','dynamicToolCall'].includes(i.type))return`<details class="tool"><summary>${esc(i.type)}</summary><pre>${esc(JSON.stringify(i,null,2))}</pre></details>`;return'';}
function cleanPath(v){return v.replace(/[\s.,:;，。；：）)\]}]+$/,'');}
function attachmentPaths(items){const found=[];for(const i of items){found.push(...((itemText(i).match(pathPattern)||[]).map(cleanPath)));if(i.type==='fileChange')for(const c of(i.changes||[]))if(/^[A-Za-z]:\\/.test(c.path||''))found.push(c.path);}return[...new Set(found)];}
function renderAttachments(turn){const files=turn.bridgeAttachments||[];if(!files.length)return'';return`<section class="attachments"><div class="attachment-heading">返回的文件</div>${files.map(file=>{const path=file.agentDiskPath||file.localPath,ext=(file.name.split('.').pop()||'').toLowerCase(),src=`/api/attachment?path=${encodeURIComponent(path)}`,direct=file.delivery!=='local_only',preview=direct&&imageExtensions.has(ext)?`<a href="${src}" target="_blank" rel="noopener"><img class="attachment-preview" src="${src}" alt="${esc(file.name)}" loading="lazy"></a>`:'',location=file.delivery==='agent_disk'?`Agent Disk：${path}`:`本机文件：${path}`,actions=direct?`<div class="attachment-actions"><a href="${src}" target="_blank" rel="noopener">查看 / 下载</a><button data-open-path="${esc(path)}">本机打开</button></div>`:`<div class="attachment-actions"><button data-open-path="${esc(path)}">本机打开</button></div>`;return`<div class="attachment-card">${preview}<div class="attachment-info"><strong>${esc(file.name)}</strong><span>${esc(location)}</span><span>${esc(file.reason||'')}</span></div>${actions}</div>`;}).join('')}</section>`;}
function bindAttachmentButtons(){document.querySelectorAll('[data-open-path]').forEach(b=>b.onclick=async()=>{const original=b.textContent;b.disabled=true;b.textContent='正在打开…';try{const r=await fetch(`/api/open-attachment?path=${encodeURIComponent(b.dataset.openPath)}`);if(!r.ok)throw new Error();b.textContent='已打开';}catch{b.textContent='文件不存在';}setTimeout(()=>{b.disabled=false;b.textContent=original;},1800);} );}
function renderTurns(turns){if(!turns.length)return'<div class="empty"><h3>暂无历史</h3><p>从飞书向该对话发送第一条消息。</p></div>';return turns.map(turn=>{const items=turn.items||[],user=items.find(x=>x.type==='userMessage'),agents=items.filter(x=>x.type==='agentMessage'),final=[...agents].reverse().find(x=>x.phase!=='commentary'),middle=items.filter(x=>x!==user&&x!==final).map(renderItem).join(''),answer=itemText(final)||(agents.length?itemText(agents.at(-1)):'（尚无最终回答）');return`<article class="turn"><div class="user"><div class="label">你</div><div class="bubble">${esc(itemText(user)||'（非文字输入）')}</div></div>${middle}<div class="assistant"><div class="label">Codex</div><div class="bubble">${esc(answer)}</div></div>${renderAttachments(turn)}</article>`;}).join('');}
async function loadThread(id,silent=false){if(threadLoading)return;threadLoading=true;selected=id;renderThreads();if(!silent)els.messages.innerHTML='<div class="loading">正在读取完整历史…</div>';try{const data=await(await fetch(`/api/thread/${encodeURIComponent(id)}`)).json();if(data.error){if(!silent)els.messages.innerHTML=`<div class="loading">${esc(data.error)}</div>`;return;}const t=data.thread,signature=JSON.stringify((t.turns||[]).map(turn=>[turn.id,turn.status,(turn.items||[]).length]));els.title.textContent=t.name||'未命名对话';els.meta.textContent=`项目：${projectName(t.cwd)} · ${t.status||'未知'} · ${(t.turns||[]).length} 轮 · ID：${t.id||id}`;if(!silent||signature!==lastThreadSignature){const nearBottom=els.messages.scrollHeight-els.messages.scrollTop-els.messages.clientHeight<140;els.messages.innerHTML=renderTurns(t.turns||[]);bindAttachmentButtons();if(!silent||nearBottom)els.messages.scrollTop=els.messages.scrollHeight;lastThreadSignature=signature;}}finally{threadLoading=false;}}
function requestFeishuCode(appId){return new Promise((resolve,reject)=>{if(!window.tt?.requestAccess){reject(new Error('请从飞书工作台打开网页应用'));return;}window.tt.requestAccess({appID:appId,scopeList:[],success:r=>resolve(r.code),fail:r=>reject(new Error(r?.errMsg||'飞书授权失败'))});});}
async function authenticate(){els.authGate.hidden=false;els.authRetry.hidden=true;els.authMessage.textContent='正在连接飞书并确认身份…';try{const config=await(await fetch('/api/auth/config',{cache:'no-store'})).json();if(!config.authRequired||config.authenticated){els.authGate.hidden=true;return true;}if(!config.ownerConfigured)throw new Error('桥尚未绑定所有者，请先在机器人单聊中发送一条消息');const code=await requestFeishuCode(config.appId);const response=await fetch('/api/auth/feishu',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const result=await response.json();if(!response.ok)throw new Error(result.error==='owner_mismatch'?'当前飞书账号不是桥的所有者':(result.message||'身份验证失败'));els.authGate.hidden=true;return true;}catch(error){els.authMessage.textContent=error.message||'身份验证失败';els.authRetry.hidden=false;return false;}}
async function boot(){if(!await authenticate())return;loadThreads();loadStatus();loadQuota();setInterval(()=>loadThreads(false),30000);setInterval(loadStatus,5000);setInterval(loadQuota,60000);setInterval(()=>{if(selected)loadThread(selected,true);},3000);}
els.authRetry.onclick=boot;els.menu.onclick=()=>document.body.classList.add('sidebar-open');els.backdrop.onclick=()=>document.body.classList.remove('sidebar-open');els.search.oninput=renderThreads;els.refresh.onclick=()=>{loadThreads();if(selected)loadThread(selected,true);};els.loadMore.onclick=()=>loadThreads(true);boot();
